name: Update Gempa

on:
  schedule:
    - cron: "0 */12 * * *" #“At minute 0 past every 12th hour.”
  push:
    branches:
      - "**"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install pandas
          pip install requests
      - name: Execute Script
        run: |
          python main.py
      - name: Commit File
        run: |
          git config --local user.email "81743021+mzakiyuddin@users.noreply.github.com"
          git config --local user.name "mzakiyuddin"
          git add .

      - name: Check is need to push
        id: check_status
        run: |
          STATUS=$(git status --porcelain | wc -l)
          echo "::set-output name=STATUS::$STATUS"

      - name: Commit File
        if: steps.check_status.outputs.STATUS == 1
        run: |
          now=$(date)
          git commit -m "Update $now"

      - name: Push Changes
        if: steps.check_status.outputs.STATUS == 1
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
